package eventDrivenLoadBalancer3.events;

public enum EventType {
	NEW_CONNECTION, NEW_ID, BATCH_IDS, FREED_ID, RESPONSE_ID, RESPONSE_BATCH_ID, BALANCE_REQUEST, BALANCE_RESPONSE, 
	NEW_SERVER_SOCKET_SERVICE, SHUTDOWN
}
