package eventDrivenLoadBalancer3.events;

public enum EventType {
	NEW_CONNECTION, NEW_ID, BATCH_IDS, FREED_ID, RESPONSE_ID, RESPONSE_BATCH_ID, BALANCE_REQUEST, NEW_CLIENT_SOCKET_SERVICE, 
	NEW_SERVER_SOCKET_SERVICE, SERVER_SOCKET_DESTROYED, SERVER_SOCKET_DESTROY, SHUTDOWN
}
